[workspace]
git_release_enable = false
dependencies_update = true # run `cargo update` in the release PR
pr_name = "release: prover v{{ version }}" # template for the PR name
pr_branch_prefix = "prover-"
git_release_body = """
{{ changelog }}
{% if remote.contributors %}
### Contributors Prover
{% for contributor in remote.contributors %}
* @{{ contributor.username }}
{% endfor %}
{% endif %}
"""
