[workspace]

# Mandatory settings
pr_name = "release: prover crates.io" # template for the PR name
pr_branch_prefix = "prover-"

# Optional settings to decide
git_release_enable = true # Whether to enable github release
dependencies_update = true # Whether to run `cargo update` in the release PR
changelog_update = true # disable changelog updates

# Aux things
pr_labels = ["release", "crates.io"]
