[package]
name = "core-bin-1"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Core bin 1"

[dependencies]
core-test-1.workspace = true
