name: Release

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:

  release-core:
    uses: ./.github/workflows/release-plz.yaml
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      cargo_registry_token: ${{ secrets.CRATES_IO_TOKEN }}
    with:
      manifest_path: 'Cargo.toml'
      config: 'release-plz.toml'

  release-prover:
    uses: ./.github/workflows/release-plz.yaml
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      cargo_registry_token: ${{ secrets.CRATES_IO_TOKEN }}
    with:
      manifest_path: 'prover/Cargo.toml'
      config: 'prover/release-plz.toml'
