name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:

  release:
    uses: matter-labs/zksync-ci-common/.github/workflows/release-please.yaml@aba-release-please-support
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      cargo_registry_token: ${{ secrets.CRATES_IO_TOKEN }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
    with:
      manifest: '.github/release-please/manifest.json'
      config: '.github/release-please/config.json'
      concurrency-suffix: 'core'
      org-owner: 'antonbaliasnikov'

#  release-prover:
#    uses: matter-labs/zksync-ci-common/.github/workflows/release-plz.yaml@v1
#    secrets:
#      gh_token: ${{ secrets.GITHUB_TOKEN }}
#      cargo_registry_token: ${{ secrets.CRATES_IO_TOKEN }}
#      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
#    with:
#      manifest_path: 'prover/Cargo.toml'
#      config: 'prover/release-plz.toml'
#      concurrency-suffix: 'prover'
#      org-owner: 'antonbaliasnikov'
